config/routes.rb
Datingapp::Application.routes.draw do
  

  resources :states

  resources :pokemongo_teams

  resources :ethnicities

  resources :profile_likes

  resources :user_messages do
    member do
      delete 'destroy', :as => "destroy_user_message"
      get 'message_conversation', :action=>'message_conversation', :as => "message_conversation"
    end
  end

  resources :user_friends

  resources :group_messages do
    member do
      get 'new_group_msg', :as => "new_group_msg"
      get 'new_group_msg_cmt', :as => "new_group_msg_cmt"
    end
  end

  resources :group_users

  resources :groups do
    member do
      get 'add_member'
      get 'add_member_to_group'
      put 'update_group_image'
    end
  end

  resources :relationships

  resources :genders

  resources :user_interests
  resources :interests

  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :sessions => "users/sessions"
  }

  resources :chat_conversations do
    resources :chat_messages
  end

  resources :landing do
    collection do
      get 'privacy'
    end
  end

  match 'users/:id/edit', :to => 'users#edit', :as => 'edit_user', :via => [:get]
  match 'users/:id', :to => 'users#update', :as => 'user', :via => [:put]

  match 'search' => 'user#search', via: [:get, :post], as: :search

  match 'users_list', :to => 'users#index', :as => 'users_list', :via => [:get]
  match 'pending_friends', :to => 'users#pending_friends', :as => 'pending_friends', :via => [:get]
  match 'add_friend', :to => 'users#add_friend', :as => 'add_friend', :via => [:get]
  match 'view_user/:id', :to => 'users#show', :as => 'view_user', :via => [:get]
  match 'settings', :to => 'users#settings', :as => 'settings', :via => [:get]
  match 'update_settings', :to => 'users#update_settings', :as => 'update_settings', :via => [:post]
  

  match 'make_profile_picture', :to => 'users#make_profile_picture', :as => 'make_profile_picture', :via => [:get]
  match 'delete_image', :to => 'users#delete_image', :as => 'delete_image', :via => [:get]
  match 'check_email_availability', :to => 'users#check_email_availability', :as => 'check_email_availability', :via => [:get]  

  match 'accept_friend', :to => 'user_friends#accept_friend', :as => 'accept_friend', :via => [:get]
  match 'accept_new_friend', :to => 'users#accept_new_friend', :as => 'accept_new_friend', :via => [:get]
  match 'remove_friend', :to => 'user_friends#remove_friend', :as => 'remove_friend', :via => [:get]
  match 'remove_sent_request', :to => 'user_friends#remove_sent_request', :as => 'remove_sent_request', :via => [:get]  

  match 'like_profile', :to => 'profile_likes#like_profile', :as => 'like_profile', :via => [:get]

  match 'new_user_msg', :to => 'user_messages#new_user_msg', :as => 'new_user_msg', :via => [:get]
  
  
  

  root :to => 'landing#index'

end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  attr_accessible :group_user_id, :is_deleted, :message, :group_id
  acts_as_commentable

  has_many :comments, :as => :commentable
  belongs_to :group
  belongs_to :user, :foreign_key=>"group_user_id", :class_name=> 'User'
end

app/controllers/group_messages_controller.rb
class GroupMessagesController < ApplicationController
  before_filter :set_group_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @group_messages = GroupMessage.all
    respond_with(@group_messages)
  end

  def show
    respond_with(@group_message)
  end

  def new
    @group_message = GroupMessage.new
    @group = Group.find(params[:group_id])
    respond_with(@group_message)
  end

  def edit
  end

  def create
    @group_message = GroupMessage.new(params[:group_message])
    @group_message.save
    respond_with(@group_message)
  end

  def new_group_msg
    @group = Group.find_by_id(params[:group_id])
    @group_message = @group.group_messages.build
    @group_message.update_attributes(:message=>params[:message],:group_user_id=>current_user.id)
    @group_message.save

    @group_messages = @group.group_messages.order("created_at DESC").includes(:comments)

    respond_to do |format|
      format.html { render :partial => "group_messages/all_group_posts", :locals=>{:group_messages=>@group_messages, :group => @group}, :layout => false}
    end 
  end

  def new_group_msg_cmt
    @group = Group.find_by_id(params[:group_id])
    group_message = GroupMessage.find_by_id(params[:group_message_id])
    comment = Comment.build_from( group_message, current_user.id, params[:comment])
    comment.save!
    respond_to do |format|
      format.html { render :partial => "group_messages/all_group_post_cmts", :locals=>{:group => @group, :group_message => group_message}, :layout => false}
    end 
  end

  def update
    @group_message.update_attributes(params[:group_message])
    respond_with(@group_message)
  end

  def destroy
    @group = @group_message.group
    @group_message.destroy
    respond_with(@group)
  end

  private
    def set_group_message
      @group_message = GroupMessage.find(params[:id])
    end
end

app/helpers/group_messages_helper.rb
module GroupMessagesHelper
end

app/views/group_messages/_all_group_post_cmts.html.erb
<ul class="commentList">
    <%group_message.try(:comments).order("created_at ASC").includes(:user=>[:attachment]).each do |comment|%>
        <li>
            <div class="commenterImage">
            <%user = comment.try(:user)%>
            <%= image_tag(user.image_path, :width => 100, :height => 100, :class=>"img-responsive") %>           
            </div>
            <div class="commentText">
                 <div class="user_name">
                    <%=user.full_name%>
                 </div>  
                <p class=""><%=comment.try(:body)%></p> <span class="date sub-text"><%=comment.created_at.in_time_zone("Chennai").strftime("%b %d, %Y at %I:%M%P.")%></span>
            </div>
        </li>
    <%end%>
</ul>
<form onSubmit="return false;" class="form-inline" role="form">
    <div class="form-group"> 
        <textarea id= "group_message_status_<%=group_message.id%>" placeholder="Your comments" rows="1" class="form-control"></textarea>
        <button onclick="createGroupPostComment(<%=group.id%>,<%=group_message.id%>)" class="btn btn-primary action-btn-add"><i class="fa fa-reply" aria-hidden="true"></i> Add</button>
    </div>
</form>

app/views/group_messages/_all_group_posts.html.erb
<br>
<div class="well"> 
	<form onSubmit="return false;" role="form" class="form-horizontal">
		<h4>What's New</h4>
		<div style="padding:14px;" class="form-group">
			<textarea id= "group_status" placeholder="Update your status" class="form-control"></textarea>
		</div>
		<button type="button" class="btn btn-primary pull-right" onclick="createGroupPost(<%=group.id%>)"><i class="fa fa-paper-plane-o" aria-hidden="true"></i> &nbsp;Post</button>
		<!-- <ul class="list-inline">
			<li><a href="#"><i class="fa fa-camera" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-smile-o" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i></a></li>
		</ul> -->
	</form>
</div>

<% group_messages.includes(:user=>[:attachment]).each do |group_message| %>
	<%is_current_user = (current_user.id == group_message.user.id)%>
	<div class="panel panel-default gc-posted-list panel-distory">
		<%if is_current_user%>
			<%#= link_to 'X', group_message, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"fa fa-times" %>
			<%=link_to group_message, method: :delete, data: { confirm: 'Are you sure?' } do%>
				<i class="fa fa-times" aria-hidden="true"></i>
			<%end%>
		<%end%>
		
		<div class="panel-heading">
			<div class="gcpl-profile-pic">
	            <%= image_tag(group_message.user.image_path, :width => 100, :height => 100, :class=>"img-responsive") %>
			</div>
			<div class="gcpl-profile-name">
				<h4><%=is_current_user ? "You have" : "#{group_message.user.first_name} has" %> shared a Post</h4>
				<p><%=group_message.created_at.in_time_zone("Chennai").strftime("%b %d, %Y at %I:%M%P.")%></p>
			</div>
		</div>
		<div class="panel-body">
			<%= group_message.message %>
		</div>
		<!-- <div class="comment-footer">
			<button type="button" class="btn btn-default btn-xs"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Like</button>
			<button type="button" class="btn btn-default btn-xs"><i class="fa fa-comments-o" aria-hidden="true"></i> Comment</button>
			<button type="button" class="btn btn-default btn-xs"><i class="fa fa-share" aria-hidden="true"></i> Share</button>
		</div> -->
		<div class="panel-footer">
			<div id="group_posts_msg_id_<%=group_message.id%>" class="actionBox">
				<%=render :partial => "group_messages/all_group_post_cmts", :locals=>{
					:group => group, :group_message => group_message}%>		        
		    </div>
		</div>
	</div>
	<!-- /.gc-posted-list -->
<%end%>


<script>
function createGroupPost(group_id){
  status = $("#group_status").val();
  if (status.trim().length != 0)
  {
	  var ajax_data = {
	    "message": status,
	    "group_id":group_id,
	  };
	  $.ajax({
	    url: "<%= new_group_msg_group_message_path %>",
	    format: "json",
	    method: "get",
	    data: ajax_data,
	    success: function(response){      
	      $("#group_posts_id").html(response);
	    }
	  });
	}
	else
	{
		alert("Please enter a Post");
	}
}

function createGroupPostComment(group_id,group_message_id){
  comment = $("#group_message_status_"+group_message_id).val();
  if (comment.trim().length != 0)
  {
  	var ajax_data = {
	    "comment": $("#group_message_status_"+group_message_id).val(),
	    "group_id":group_id,
	    "group_message_id":group_message_id,
	  };
	  $.ajax({
	    url: "<%= new_group_msg_cmt_group_message_path %>",
	    format: "json",
	    method: "get",
	    data: ajax_data,
	    success: function(response){      
	      $("#group_posts_msg_id_"+group_message_id).html(response);
	    }
	  });
	}
	else
	{
		alert("Please enter a comment");
	}
}
</script>

app/views/group_messages/_form.html.erb
<%= form_for(@group_message) do |f| %>
  <% if @group_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_message.errors.count, "error") %> prohibited this group_message from being saved:</h2>

      <ul>
      <% @group_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :group_user_id %><br />
    <%= f.hidden_field :group_user_id, :value=> current_user.id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%#= f.label :is_deleted %><br />
    <%#= f.check_box :is_deleted %>
  </div>
  <%= f.hidden_field :group_id, :value=> @group.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_messages/edit.html.erb
<h1>Editing group_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_message %> |
<%= link_to 'Back', group_messages_path %>

app/views/group_messages/index.html.erb
<h1>Listing group_messages</h1>

<table>
  <tr>
    <th>Group user</th>
    <th>Message</th>
    <th>Is deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_messages.each do |group_message| %>
  <tr>
    <td><%= group_message.group_user_id %></td>
    <td><%= group_message.message %></td>
    <td><%= group_message.is_deleted %></td>
    <td><%= link_to 'Show', group_message %></td>
    <td><%= link_to 'Edit', edit_group_message_path(group_message) %></td>
    <td><%= link_to 'Destroy', group_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group message', new_group_message_path %>

app/views/group_messages/new.html.erb
<h1>New group_message</h1>

<%= render 'form' %>

<%= link_to 'Back', group_messages_path %>

app/views/group_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group user:</b>
  <%= @group_message.group_user_id %>
</p>

<p>
  <b>Message:</b>
  <%= @group_message.message %>
</p>

<p>
  <b>Is deleted:</b>
  <%= @group_message.is_deleted %>
</p>


<%= link_to 'Edit', edit_group_message_path(@group_message) %> |
<%= link_to 'Back', group_messages_path %>