config/routes.rb
Datingapp::Application.routes.draw do
  

  resources :states

  resources :pokemongo_teams

  resources :ethnicities

  resources :profile_likes

  resources :user_messages do
    member do
      delete 'destroy', :as => "destroy_user_message"
      get 'message_conversation', :action=>'message_conversation', :as => "message_conversation"
    end
  end

  resources :user_friends

  resources :group_messages do
    member do
      get 'new_group_msg', :as => "new_group_msg"
      get 'new_group_msg_cmt', :as => "new_group_msg_cmt"
    end
  end

  resources :group_users

  resources :groups do
    member do
      get 'add_member'
      get 'add_member_to_group'
      put 'update_group_image'
    end
  end

  resources :relationships

  resources :genders

  resources :user_interests
  resources :interests

  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :sessions => "users/sessions"
  }

  resources :chat_conversations do
    resources :chat_messages
  end

  resources :landing do
    collection do
      get 'privacy'
    end
  end

  match 'users/:id/edit', :to => 'users#edit', :as => 'edit_user', :via => [:get]
  match 'users/:id', :to => 'users#update', :as => 'user', :via => [:put]

  match 'search' => 'user#search', via: [:get, :post], as: :search

  match 'users_list', :to => 'users#index', :as => 'users_list', :via => [:get]
  match 'pending_friends', :to => 'users#pending_friends', :as => 'pending_friends', :via => [:get]
  match 'add_friend', :to => 'users#add_friend', :as => 'add_friend', :via => [:get]
  match 'view_user/:id', :to => 'users#show', :as => 'view_user', :via => [:get]
  match 'settings', :to => 'users#settings', :as => 'settings', :via => [:get]
  match 'update_settings', :to => 'users#update_settings', :as => 'update_settings', :via => [:post]
  

  match 'make_profile_picture', :to => 'users#make_profile_picture', :as => 'make_profile_picture', :via => [:get]
  match 'delete_image', :to => 'users#delete_image', :as => 'delete_image', :via => [:get]
  match 'check_email_availability', :to => 'users#check_email_availability', :as => 'check_email_availability', :via => [:get]  

  match 'accept_friend', :to => 'user_friends#accept_friend', :as => 'accept_friend', :via => [:get]
  match 'accept_new_friend', :to => 'users#accept_new_friend', :as => 'accept_new_friend', :via => [:get]
  match 'remove_friend', :to => 'user_friends#remove_friend', :as => 'remove_friend', :via => [:get]
  match 'remove_sent_request', :to => 'user_friends#remove_sent_request', :as => 'remove_sent_request', :via => [:get]  

  match 'like_profile', :to => 'profile_likes#like_profile', :as => 'like_profile', :via => [:get]

  match 'new_user_msg', :to => 'user_messages#new_user_msg', :as => 'new_user_msg', :via => [:get]
  
  
  

  root :to => 'landing#index'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	before_filter :authenticate_user!, :except=>[:privacy]

	def index
		@q = User.ransack(params[:q])
    	@res = @q.result.includes(:interests, :groups)
		# @accepted_friends, @friends_request = UserFriend.friends_and_requests(current_user.id)		
		@accepted_friends = UserFriend.accepted_friends(current_user.id)
		@sent_requests = UserFriend.sent_requests(current_user.id)
	end

	def privacy
	end
end

app/views/landing/_accepted_friends.html.erb
<%if accepted_friends.length==0%>	
	<div class="<%=custom_class%>">		
		<div class="border-title">
			<span id="span_mutual_friends">NO POKES YET</span>
		</div>
	</div>

<%else%>
	<div class="<%=custom_class%>">
		<%unless index_page%>
		<div class="border-title">
			<%if check_current_profile_id.to_i==current_user.id%>	    		
	    		<h4>My Pokes (<%=UserFriend.total_friends_count(check_current_profile_id)%>)</h4>
	    	<%else%>
	    		<span id="span_mutual_friends">MUTUAL FRIENDS</span>
	    	<%end%>				
		</div>
		<%end%>
		<div class="friends-listing">
			<div class="row">
				<%mutual_friends_count=0%>
				<% accepted_friends.each_with_index do |my_friend,counter| %>	
					<%target_user = my_friend.user%>
					<%if dont_check_if_friend or my_friends_id.include? target_user.id%>
			        	<%mutual_friends_count+=1%>
			        	<% if custom_class2 %>
						<div class="col-md-<%=custom_class1%> col-sm-<%=custom_class2%> col-xs-<%=custom_class2%>">
						<% else %>
						<div class="col-md-<%=custom_class1%> col-sm-<%=custom_class1%> col-xs-<%=custom_class1%>">
						<% end %>
							<div class="friends-listing-box">					
								<div class="col-md-4 col-sm-4 col-xs-4 p_z">
									<a class="profile-image" title="Profile Image" href="javascript:;">
										<%=image_tag(target_user.image_path, :alt=>"")%>
									</a>
								</div>
								<div class="col-md-8 col-sm-8 col-xs-8 p_z">
									<div class="friends-details">
										<h3>
											<a href="<%=view_user_path(target_user)%>"><%=target_user.full_name(true)%>
											</a>
										</h3>
										<a href="javascript:;"><%=target_user.user_friends.find_all{|item| item.is_accepted==true}.length%> friends</a>
										<ul>
											<%unless target_user.relationship_interest_icon.nil?%>
												<li>
													<a href="javascript:;" style="cursor:default">						
														<%=image_tag(target_user.relationship_interest_icon, :title=>target_user.relationship_interest.name)%>
													</a>
												</li>
											<%end%>
											<%unless target_user.team_icon.nil?%>
												<li>
													<a href="javascript:;" style="cursor:default">						
														<%=image_tag(target_user.team_icon, :title=>target_user.team_name)%>
													</a>
												</li>
											<%end%>
											<li>
												<a href="<%=message_conversation_user_message_path(current_user)%>?uid=<%= target_user.id%>">	
													<%=image_tag("/assets/message.png", :title=>"Messaging")%>
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					<%end%>
				<%end%>
				<%if mutual_friends_count==0%>
		        	<script>
		        		$("#span_mutual_friends").hide();
		        	</script>
	        	<%end%>
	        </div>
	    </div>
	</div>
<%end%>

app/views/landing/_app_download.html.erb
<div class="content_middle wow fadeInUp" data-wow-delay="0.4s">
  <div class="container">
     <div class="col-md-9 grid_2">
        <h3>Start Dating Now !</h3>
        <h4>Download our mobile apps and start dating right now.</h4>
        <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore.</p>
        <ul class="apps wow fadeInLeft" data-wow-delay="0.4s">
        <li><a href="#"><i class="app"></i></a></li>
      <li><a href="#"><i class="google"></i></a></li>
      </ul>
       <h5>OR</h5>
       <a href="#" class="btn3 btn-3 btn3-1b">Sign Up</a>
     </div>
     <div class="col-md-3 grid_3 wow fadeInRight" data-wow-delay="0.4s">
         <span> </span>
     </div>
  </div>
</div>

app/views/landing/_banner.html.erb
<div class="profile_banner">
  <div class="container"> 
    <div class="row">
      <div class="col-md-5">
          <h2 class="section-title">Just make some new friends</h2>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's </p>
          <a href="<%=user_friends_path%>" class="btn btn-raised btn-bordered">MY POKES</a>
      </div>
      <div class="col-md-7">
        <div class="pro-search-box">
          <%= search_form_for @q, url: users_list_path,
                        html: { method: :get } do |f| %>
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="form-group">                  
                  <%= f.select :gender_id_eq, options_for_select( Gender.order(:name).map{ |c| [c.name, c.id] }, params[:q].present? && params[:q]["gender_id_eq"] ? params[:q]["gender_id_eq"] : []), {:include_blank => 'I am seeking'}, { :class => 'selectDropdown form-control'} %>
                </div>
              </div>
               <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="form-group">
                  <%= f.select :relationship_interest_id_eq, options_for_select( RelationshipInterest.all.map{ |c| [c.name, c.id] }, params[:q].present? && params[:q]["relationship_interest_id_eq"] ? params[:q]["relationship_interest_id_eq"] : []), {:include_blank => 'For'}, { :class => 'selectDropdown form-control'}  %>
                </div>                
              </div>
              <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="form-group">
                  <%= f.select :age_cont, options_for_select(age_group, params[:q].present? && params[:q]["age_cont"] ? params[:q]["age_cont"] : []), {:include_blank => 'Age Group'}, { :class => 'selectDropdown form-control'}%>
                </div>
              </div>             
              <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="form-group">
                  <%= f.search_field :city_cont, class: 'form-control', :placeholder=>"City" %>
                </div>              
              </div>
              <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="form-group">
                  <%= f.select :state_id_eq, options_for_select( State.order(:name).map{ |c| [c.name, c.id] }, params[:q].present? && params[:q]["state_id_eq"] ? params[:q]["state_id_eq"] : []), {:include_blank => 'Any State'}, { :class => 'selectDropdown form-control'}  %>
                </div>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-6">              
                  <div class="form-group label-floating">         
                    <%= f.text_field :zip_code_eq, class: 'form-control', :placeholder=>"Zip Code", :maxLength=>"5", :onkeypress=>'return event.charCode >= 48 && event.charCode <= 57' %>
                  </div>              
              </div>
            </div>
            <div class="text-center">
            <%= f.submit "Search", :class=>"btn btn-raised btn-bordered btn-blue" %>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/landing/_how_works_pop.html.erb
<!-- How works Modal -->
<div class="modal fade" id="howWorks" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">How it works</h4>
            </div>
            <div class="modal-body">
                <p>Are you a fan of Pokemon Go, then this is the right place to get yourself more excited with new friends of similar interest.</p><br/>
                <p>After signing up, you can find number of other players who might also want to find new pokes.</p><br/>
                <p>Get yourself embraced with lot of excitement with new pokes. Happy Dating..</p>
            </div>
        </div>
    </div>
</div>
<!-- /.modal -->

app/views/landing/_looking_for_someone.html.erb
<div class="profile_banner">
  <div class="container"> 
     <h3>Looking for someone</h3>
  </div>
</div>

  <div class="container">      
    <div class="search wow">
      <div class="register">
      <div class="register-but">
          <%= search_form_for @q, url: users_list_path,
                        html: { method: :get } do |f| %>
         <div class="register-top-grid">
          <!-- <h3>LOOKING FOR SOMEONE</h3><br/> -->
          <div class="row">
            <div class="form-group col-md-4"><!-- <span>Gender</span> -->
              <%= f.select :gender_id_eq, options_for_select( Gender.order(:name).map{ |c| [c.name, c.id] }, params[:q].present? && params[:q]["gender_id_eq"] ? params[:q]["gender_id_eq"] : []), {:include_blank => 'Any Gender'}, { :class => 'form-control'} %>
            </div>
            <div class="form-group col-md-2"><!-- <span>Age From</span> -->
            <%= f.number_field :age_gteq, class: 'form-control', :placeholder=>"Age From", min: 1, oninput: "validity.valid||(value='');"%></div>
            <div class="form-group col-md-2"><!-- <span>Age To</span>  -->             
             <%= f.number_field :age_lteq, class: 'form-control', :placeholder=>"Age To", min: 1, oninput: "validity.valid||(value='');"%> </div>
             <div class="form-group col-md-4"><!-- <span>Seeking</span> -->
              <%= f.select :relationship_interest_id_eq, options_for_select( RelationshipInterest.all.map{ |c| [c.name, c.id] }, params[:q].present? && params[:q]["relationship_interest_id_eq"] ? params[:q]["relationship_interest_id_eq"] : []), {:include_blank => 'I am Seeking'}, { :class => 'form-control'}  %>
            </div>            
            <div class="form-group col-md-4"><!-- <span>City</span> -->
             <%= f.search_field :city_cont, class: 'form-control', :placeholder=>"City" %> </div>
             <div class="form-group col-md-4"><!-- <span>State</span> -->
              <%= f.select :state_id_eq, options_for_select( State.order(:name).map{ |c| [c.name, c.id] }, params[:q].present? && params[:q]["state_id_eq"] ? params[:q]["state_id_eq"] : []), {:include_blank => 'Any State'}, { :class => 'form-control'}  %>
            </div>
            <div class="form-group col-md-4"><!-- <span>Zip Code</span> -->
             <%= f.search_field :zip_code_eq, class: 'form-control', :placeholder=>"Zip Code" %> </div>
            <div class="form-group col-md-12" style="margin-top:20px;"><%= f.submit "Search" %></div>
          </div>  
        </div>
        <%end%>
      </div>
    </div>
      </div>
   </div>

<script>
  function fnSearch(){
    //$.post('http://example.com/upload', function() {
      if($("#txtSearch").val().trim()!=""){
        window.location.href =  "<%=users_list_path%>" + "?first_name="+$("#txtSearch").val();
      }
        

    //});
  }


  // $(document).ready(function() {
  //   var availableTags = [
  //     "ActionScript",
  //     "AppleScript",
  //     "Asp",
  //     "BASIC",
  //     "C",
  //     "C++",
  //     "Clojure",
  //     "COBOL",
  //     "ColdFusion",
  //     "Erlang",
  //     "Fortran",
  //     "Groovy",
  //     "Haskell",
  //     "Java",
  //     "JavaScript",
  //     "Lisp",
  //     "Perl",
  //     "PHP",
  //     "Python",
  //     "Ruby",
  //     "Scala",
  //     "Scheme"
  //   ];
  //   $( "#txtSearch" ).autocomplete({
  //     source: availableTags
  //   });
  // } );
  </script>

app/views/landing/_my_friends.html.erb
<div class="friends-section">
	<div class="container">
		<div class="row">
				
		    <%= render :partial => "landing/accepted_friends", :locals =>{:accepted_friends => @accepted_friends, :custom_class => @sent_requests.length==0 ? "col-md-12" : "col-md-8", :custom_class1 => @sent_requests.length==0 ? "4" : "6", :custom_class2 => false, :check_current_profile_id => current_user.id, :dont_check_if_friend => true, :index_page=>false} %>



			<%#= render :partial => "user_friends/recvd_frnd_requests" %>
			<%= render :partial => "user_friends/sent_requests" %>


			
		</div>
	</div>
</div>
<style>
p.accept{
	color: #668014;
}
p.reject{
	color: #EE2C2C;
}
</style>

app/views/landing/index.html.erb
<%= render :partial => 'banner' %>

<%#= render :partial => 'looking_for_someone' %>

<div id="divFriends">
  <%= render :partial => 'my_friends' %>
</div>

<%#= render :partial => 'love_story' %>

<%#= render :partial => 'app_download' %>

  
<script>
// function fnUpdateFriendRequestStatus(friend_request_id,acceptance_status){
//   var ajax_data = {
//     "id":friend_request_id,
//     "acceptance_status":acceptance_status
//   };
//   $.ajax({
//     url: "<%= accept_friend_path %>",
//     format: "json",
//     data: ajax_data,
//     success: function(response){
//       $("#divFriends").html(response);
//     }
//   });
// }

function fnGoToUsersList(){
  window.location.href="<%=users_list_path%>";
}

function fnGoToMyPokes(){
  window.location.href="<%=user_messages_path%>";
}

function fnGoToMyGroups(){
 // window.location.href="<%#=groups_path%>";
}
</script>