config/routes.rb
Datingapp::Application.routes.draw do
  

  resources :states

  resources :pokemongo_teams

  resources :ethnicities

  resources :profile_likes

  resources :user_messages do
    member do
      delete 'destroy', :as => "destroy_user_message"
      get 'message_conversation', :action=>'message_conversation', :as => "message_conversation"
    end
  end

  resources :user_friends

  resources :group_messages do
    member do
      get 'new_group_msg', :as => "new_group_msg"
      get 'new_group_msg_cmt', :as => "new_group_msg_cmt"
    end
  end

  resources :group_users

  resources :groups do
    member do
      get 'add_member'
      get 'add_member_to_group'
      put 'update_group_image'
    end
  end

  resources :relationships

  resources :genders

  resources :user_interests
  resources :interests

  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :sessions => "users/sessions"
  }

  resources :chat_conversations do
    resources :chat_messages
  end

  resources :landing do
    collection do
      get 'privacy'
    end
  end

  match 'users/:id/edit', :to => 'users#edit', :as => 'edit_user', :via => [:get]
  match 'users/:id', :to => 'users#update', :as => 'user', :via => [:put]

  match 'search' => 'user#search', via: [:get, :post], as: :search

  match 'users_list', :to => 'users#index', :as => 'users_list', :via => [:get]
  match 'pending_friends', :to => 'users#pending_friends', :as => 'pending_friends', :via => [:get]
  match 'add_friend', :to => 'users#add_friend', :as => 'add_friend', :via => [:get]
  match 'view_user/:id', :to => 'users#show', :as => 'view_user', :via => [:get]
  match 'settings', :to => 'users#settings', :as => 'settings', :via => [:get]
  match 'update_settings', :to => 'users#update_settings', :as => 'update_settings', :via => [:post]
  

  match 'make_profile_picture', :to => 'users#make_profile_picture', :as => 'make_profile_picture', :via => [:get]
  match 'delete_image', :to => 'users#delete_image', :as => 'delete_image', :via => [:get]
  match 'check_email_availability', :to => 'users#check_email_availability', :as => 'check_email_availability', :via => [:get]  

  match 'accept_friend', :to => 'user_friends#accept_friend', :as => 'accept_friend', :via => [:get]
  match 'accept_new_friend', :to => 'users#accept_new_friend', :as => 'accept_new_friend', :via => [:get]
  match 'remove_friend', :to => 'user_friends#remove_friend', :as => 'remove_friend', :via => [:get]
  match 'remove_sent_request', :to => 'user_friends#remove_sent_request', :as => 'remove_sent_request', :via => [:get]  

  match 'like_profile', :to => 'profile_likes#like_profile', :as => 'like_profile', :via => [:get]

  match 'new_user_msg', :to => 'user_messages#new_user_msg', :as => 'new_user_msg', :via => [:get]
  
  
  

  root :to => 'landing#index'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_mailbox
  before_filter :get_conversation, except: [:index, :empty_trash]
  before_filter :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
	    @conversations = @mailbox.inbox
	  elsif @box.eql? "sent"
	    @conversations = @mailbox.sentbox
	  else
	    @conversations = @mailbox.trash
	  end
	  @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def reply
	  current_user.reply_to_conversation(@conversation, params[:body])
	  flash[:notice] = 'Reply sent'
	  redirect_to conversation_path(@conversation)
  end

  def destroy
	  @conversation.move_to_trash(current_user)
	  flash[:notice] = 'The conversation was moved to trash.'
	  redirect_to conversations_path
  end

  def restore
	  @conversation.untrash(current_user)
	  flash[:notice] = 'The conversation was restored.'
	  redirect_to conversations_path
  end

  def empty_trash
	  @mailbox.trash.each do |conversation|
	    conversation.receipts_for(current_user).update_all(deleted: true)
	  end
	  flash[:notice] = 'Your trash was cleaned!'
	  redirect_to conversations_path
  end
 
  def mark_as_read
		@conversation.mark_as_read(current_user)
		flash[:notice] = 'The conversation was marked as read.'
		redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
	  if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
	    params[:box] = 'inbox'
	  end
	  @box = params[:box]
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
	def mailbox_section(title, current_box, opts = {})
	    opts[:class] = opts.fetch(:class, '')
	    opts[:class] += ' active' if title.downcase == current_box
	    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
	end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= sender_name(conversation).titleize%>: 
  &nbsp;
  <%= link_to read_more(conversation.subject, 100), conversation_path(conversation) %> 
  &nbsp;
  <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>

  <div class="pull-right">
    	<% if conversation.is_trashed?(current_user) %>
	    	<%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
	  <% else %>    	              

	   		<% if conversation.is_unread?(current_user) %>
	   			<%if params[:box] && params[:box] != "sent" %>
	      			<%= link_to '<i class="fa fa-check" aria-hidden="true"></i> '.html_safe, mark_as_read_conversation_path(conversation),
	                  class: 'btn btn-xs btn-info', method: :post, :title => "Mark as read" %>
	            <% end %>
	    <% end %>
	    <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> '.html_safe, conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete, :title => "Move to trash",
	                data: {confirm: 'Are you sure?'}  %>  
	  <% end %>
  </div>

  <p><%#= render 'conversations/participant', conversation: conversation %></p>
    	<div class="body_of_message">
	    	<p>
			     <% if conversation.last_message.body.length > 100 %>	     
				    <%= read_more(conversation.last_message.body, 100) %>
				    <%= link_to_function 'Read more', "$(this).parent().html('#{escape_javascript conversation.last_message.body}')" %>
				 <% else %>
				    <%= conversation.last_message.body %>
				 <% end %>
			</p>
	    </div>
</li>

app/views/conversations/_participant.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= gravatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="content_top">
  <div class="container">
	<% page_header "Your Conversations" %>
	<div class="row">
	  <div class="col-sm-3">
	    <ul class="nav nav-pills nav-stacked">
	      <%= link_to 'Compose', new_message_path, class: 'btn btn-primary' %>
	      <br/>
	      <br/>
	      <%= mailbox_section 'inbox'+"(#{current_user.unread_inbox_count})", @box, class: @box == "inbox" ? "active" : "" %>
	      <%= mailbox_section 'sent', @box %>
	      <%= mailbox_section 'trash', @box %>
	    </ul>
	  </div>

	  <div class="col-sm-9">
		   <% if @box == 'trash' %>
		    <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
		                   data: {confirm: 'Are you sure?'} %></p>
		  <% end %>
		  <ul class="list-group">
		    <%= render partial: 'conversations/conversation', collection: @conversations %>
		    <br/>
		    <%= "No message found!" if @conversations.length == 0%>
		     <br/>
		  </ul>

	    <%= will_paginate %>
	  </div>
	</div>
 </div>
</div>

app/views/conversations/show.html.erb
<div class="profile_banner">
  <div class="container"> 
     <h3>View Message</h3>
  </div>
</div>
<div class="content_top">
  <div class="container">
<% page_header "Conversation" %>

<p>Chatting with
  <%= render 'conversations/participant', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <%= gravatar_for message.sender, 45, message.sender.name %>
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.first_name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
        <div class="form-group">
          <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
        </div>
        <%= submit_tag "Reply", class: 'btn btn-primary' %>
        <%= link_to 'Back', conversations_path, class: 'btn btn-danger'%>
    <% end %>
  </div>
  </div>
</div>
</div>