config/routes.rb
Datingapp::Application.routes.draw do
  

  resources :states

  resources :pokemongo_teams

  resources :ethnicities

  resources :profile_likes

  resources :user_messages do
    member do
      delete 'destroy', :as => "destroy_user_message"
      get 'message_conversation', :action=>'message_conversation', :as => "message_conversation"
    end
  end

  resources :user_friends

  resources :group_messages do
    member do
      get 'new_group_msg', :as => "new_group_msg"
      get 'new_group_msg_cmt', :as => "new_group_msg_cmt"
    end
  end

  resources :group_users

  resources :groups do
    member do
      get 'add_member'
      get 'add_member_to_group'
      put 'update_group_image'
    end
  end

  resources :relationships

  resources :genders

  resources :user_interests
  resources :interests

  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :sessions => "users/sessions"
  }

  resources :chat_conversations do
    resources :chat_messages
  end

  resources :landing do
    collection do
      get 'privacy'
    end
  end

  match 'users/:id/edit', :to => 'users#edit', :as => 'edit_user', :via => [:get]
  match 'users/:id', :to => 'users#update', :as => 'user', :via => [:put]

  match 'search' => 'user#search', via: [:get, :post], as: :search

  match 'users_list', :to => 'users#index', :as => 'users_list', :via => [:get]
  match 'pending_friends', :to => 'users#pending_friends', :as => 'pending_friends', :via => [:get]
  match 'add_friend', :to => 'users#add_friend', :as => 'add_friend', :via => [:get]
  match 'view_user/:id', :to => 'users#show', :as => 'view_user', :via => [:get]
  match 'settings', :to => 'users#settings', :as => 'settings', :via => [:get]
  match 'update_settings', :to => 'users#update_settings', :as => 'update_settings', :via => [:post]
  

  match 'make_profile_picture', :to => 'users#make_profile_picture', :as => 'make_profile_picture', :via => [:get]
  match 'delete_image', :to => 'users#delete_image', :as => 'delete_image', :via => [:get]
  match 'check_email_availability', :to => 'users#check_email_availability', :as => 'check_email_availability', :via => [:get]  

  match 'accept_friend', :to => 'user_friends#accept_friend', :as => 'accept_friend', :via => [:get]
  match 'accept_new_friend', :to => 'users#accept_new_friend', :as => 'accept_new_friend', :via => [:get]
  match 'remove_friend', :to => 'user_friends#remove_friend', :as => 'remove_friend', :via => [:get]
  match 'remove_sent_request', :to => 'user_friends#remove_sent_request', :as => 'remove_sent_request', :via => [:get]  

  match 'like_profile', :to => 'profile_likes#like_profile', :as => 'like_profile', :via => [:get]

  match 'new_user_msg', :to => 'user_messages#new_user_msg', :as => 'new_user_msg', :via => [:get]
  
  
  

  root :to => 'landing#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  groupify :group, members: [:users], default_members: :users

  attr_accessible :name, :description, :attachment, :attachment_attributes

  has_one :attachment, :as => :attachable
  has_many :group_messages, :dependent => :destroy

  accepts_nested_attributes_for :attachment, allow_destroy: true

  def image_path
    if attachment.nil?
      "/assets/default_image.png"
    else
      "http://osdevelopment.techaffinity.com/social-dating/"  << attachment.attachment.to_s
    end
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :set_group, only: [:show, :edit, :update, :destroy, :update_group_image, :add_member, :add_member_to_group]

  respond_to :html

  def index
    @groups = Group.where(:id=> (GroupMembership.where(:member_id=>current_user.id,:member_type=>"User",:is_deleted=>false).first.group_id))
     #current_user.groups.joins(:group_memberships).where("groups.group_memberships.is_deleted=false")
     # @groups = Group.with_member(current_user)
    respond_with(@groups)
  end

  def show
    @group_users = @group.users.includes(:user_friends)
    @group_messages = @group.group_messages.order("created_at DESC").includes(:comments)
    @group_friends = UserFriend.friends_id(current_user)
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(params[:group])
    @group.save
    respond_with(@group)
  end

  def update
    @group.update_attributes(params[:group])
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  def add_member
    @user_friends = current_user.user_friends
    group_members = User.in_group(@group).pluck(:id)

    @my_friends = User.where(:id=>(@user_friends.pluck(:friend_id) - group_members))
    respond_with(@my_friends)
  end

  def add_member_to_group
    @user = User.find_by_id(params[:friend_id])
    @group.add @user

    @user_friends = current_user.user_friends
    group_members = User.in_group(@group).pluck(:id)
    @my_friends = User.where(:id=>(@user_friends.pluck(:friend_id) - group_members))
    respond_to do |format|
      format.html { render :partial => "friends_list", :locals=>{:my_friends=>@my_friends, :group=>@group}, :layout => false}
    end
    # redirect_to add_member_group_path(@group)
  end

  def update_group_image
    respond_to do |format|
      if @group.update_attributes!(params[:group])
        format.html { redirect_to group_path(@group), notice: 'Group Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to group_path(@group), notice: 'Group Image was not successfully updated.' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
    # respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="profile_banner">
  <div class="container"> 
     <h3>Add New Group</h3>
  </div>
</div>
<div class='profiles'>
  <div class="container">
    <div class="account_grid">
       <div class="col-md-6 login-right">
          <h3>New Group</h3>
        <p>Please create a new group and add new members to collaborate.</p>
        <%= form_for(@group) do |f| %>
        <% if @group.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
            <ul>
            <% @group.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
          <div>
          <span>Group Name<label>*</label></span>
          <%= f.text_field :name, autofocus: true, :class=>"form-control", :required=> "true" %>
          </div>
          <div>
          <span>Description<label>*</label></span>
          <%= f.text_field :description, autofocus: true, :class=>"form-control", :required=> "true" %>
          </div>
          <%= f.submit "Submit", :class=>"btn btn-primary" %>
          <%= link_to 'Back', groups_path , :class=>"btn btn-primary" %>
          <% end %>
          
       </div> 
       <div class="clearfix"> </div>
     </div>
  </div>
</div>

app/views/groups/_friends_list.html.erb
<div class="content_bottom">
  <div class="container">
    <div class="box1">
       <%if my_friends.length==0%>
    	<h4>No new friends available</h4>
       <%end%>
       <% my_friends.each_with_index do |user,counter| %>
        <div class="col-md-4 wow fadeInLeft" data-wow-delay="0.4s">
          <div class="grid_4">
            <a href="#">
              <h4><span class="m_3"><a href="<%=view_user_path(user)%>"><%=user.full_name%></a></span></h4>
              <%=image_tag("/assets/pic#{(counter%9)+1}.jpg", :class=>"img-responsive", :alt=>"")%>
              <a href="#" class="btn1 btn4 btn-1 btn1-1b" onclick="addToGroup(<%=user.id%>,<%=group.id%>)">Add to Group</a>
            </a> 
          </div>
        </div>
      <%end%>
      <div class="clearfix"> </div>
    </div>
    <div class='clearfix'> </div>
  </div>
</div>

app/views/groups/_group_members.html.erb
<%if @group_users.length==0%>
	<h4 class="m_4">No members added yet.</h4>
	<br/>	
<%else%>
	<div class="<%=custom_class%>">		    	
	    <h4 class="recent">GROUP MEMBERS(<%=@group_users.length%>)</h4>
	    <div class="my-friend-list">
	    	<div class="row">
	    		<% @group_users.each_with_index do |group_member,counter| %>	
		        	<div class="<%=custom_class1%>">
				        <div class="well">
			                <div class="media">
			                    <a class="thumbnail pull-left" href="#">
			                    	<%=image_tag(group_member.image_path, :class=>"img-responsive", :alt=>"")%>
			                    </a>
			                    <div class="media-body">
			                        <h4 class="media-heading"><a href="<%=view_user_path(group_member)%>"><%=group_member.full_name%>
									</a></h4>
			                		<p class="run-text"><%=group_member.user_friends.find_all{|item| item.is_accepted==true}.length%> friends</p>
			                		<% if current_user.id!=group_member.id && @group_friends.include?(group_member.id)%>
				                        <p>
				                            <a href="<%=new_user_message_path%>?uid=<%= group_member.id%>" class="btn btn-xs btn-default">
				                            	<i class="fa fa-envelope-o" aria-hidden="true"></i> Mail
				                            </a>
				                            <a href="#" class="btn btn-xs btn-default start-conversation" data-sid="<%=current_user.id%>" data-rip="<%=group_member.id%>">
				                            	<i class="fa fa-comments-o" aria-hidden="true"></i> Chat
				                            </a>
				                        </p>
			                        <%end%>
			                    </div>
			                </div>
			            </div>
		            </div>		        
	        	<%end%>
	        </div>
	    </div>
	</div>
<%end%>
<!-- 
<a href="<%#=add_member_group_path(group)%>" class="btn1 btn4 btn-1 btn1-1b">Add New Member</a> -->

app/views/groups/add_member.html.erb
<div id="divUsersList">
  <%= render :partial => "friends_list", :locals=>{:my_friends=>@my_friends, :group=>@group} %>
</div>
<script>
function addToGroup(friend_id,group_id){   
  var ajax_data = {
    "friend_id":friend_id,
    "group_id":group_id,
  };
  $.ajax({
    url: "<%= add_member_to_group_group_path %>",
    format: "json",
    data: ajax_data,
    success: function(response){      
      $("#divUsersList").html(response);
    }
  });
}

</script>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<div class='profiles'>
  <div class="container">
    <div class="about_box1">
      <h1 class="m_4 wow flipInX" data-wow-delay="0.4s">
          My Groups
        </h1>
        <p class="m_5 wow flipInY" data-wow-delay="0.4s">
           collaborate with your friends
        </p>
        <% @groups.each do |group| %>
         <div class="about_grid1">
            <div class="col-md-4 grid_1 wow lightSpeedIn" data-wow-delay="0.4s"> 
               
                <%= link_to(image_tag(group.image_path, :alt => "Group image", :width => 100, :height => 100), group, :class=>"img-responsive") %>
                  <div class="btn-wrap bg_2">
                       <p class="text_2 bg_1 color_2">
                            <span><%=group.try(:name).try(:capitalize)%></span>
                       </p>
                           <span><%= link_to "#{group.users.count} Members", group, :class=>"text_3 color_3"%></span>
                  </div>
                  <p class="m_9"><%=group.try(:description)%></p>
            </div>
          <%end%>
          <!-- <div class="col-md-4 grid_1 wow rotateIn " data-wow-delay="0.4s"> 
             <img src="assets/pic6.jpg" class="img-responsive" alt=""/>
                <div class="btn-wrap bg_2">
                     <p class="text_2 bg_1 color_2">
                          <span>Step Two</span>
                     </p>
           <a href="#" class="text_3 color_3">
                         <span>5 Members</span>
                     </a>
                </div>
                <p class="m_9">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.</p>
          </div>
         <div class="col-md-4 grid_1 wow rotateInDownLeft" data-wow-delay="0.4s"> 
             <img src="assets/pic7.jpg" class="img-responsive" alt=""/>
                <div class="btn-wrap bg_2">
                     <p class="text_2 bg_1 color_2">
                          <span>Step Three</span>
                     </p>
           <a href="#" class="text_3 color_3">
                         <span>7 Members</span>
                     </a>
                </div>
                <p class="m_9">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.</p>
          </div> -->
          <div class="clearfix"> </div>
       </div>
       <!-- <div class="profile_button wow rotateInUpLeft" data-wow-delay="0.4s">
       <%#= link_to 'Add Group', new_group_path, :class=>"btn1 btn4 btn-1 btn1-1b" %>
       </div> -->
       <br/>
  </div>
</div>
</div>








<!-- 


<%# @groups.each do |group| %>
  <tr>
    <td><%#= link_to 'Edit', edit_group_path(group) %></td>
    <td><%#= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<%# end %>
 -->

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<div class="profile">
  <div class="container">
	  <div class="col-md-8">
	  	<div class="group-conversation">
		  	<div class="panel panel-default gc-banner">
			    <div class="panel-thumbnail">
			    	<img class="img-responsive" src="http://www.bootply.com/assets/example/bg_5.jpg" />
			    	<div class="gc-banner-overlay"></div>
			    </div>
			    <div class="panel-body">
			    	<%#= form_for(@group, url: update_group_image_group_path(@group), :method=>:put, multiple: true) do |f| %>
				    	<div class="gc-profile-pic">
				            <%= link_to(image_tag(@group.image_path, :alt => "Group image", :width => 100, :height => 100, :class=>"img-responsive")) %>
				          	<%#= f.fields_for :attachment_attributes do |attachment_f| %>
			                	<%#= attachment_f.file_field :attachment %>
			            	<%#end%>
			            	<%#= f.submit "Upload" %>
				    	</div> 
			         	
			    	<%# end %>
			    	<div class="gc-profile-name">
			    		<div class="gc-profile-name-in">
			    			<h2><strong><%=@group.name%>,</a>&nbsp;<%=@group.try(:description)%></strong></h2>
			    			<p><%=@group.users.count%> Followers, <%=@group.group_messages.count%> Posts</p>
			    		</div>
			    		<!-- <div class="btn-groups">
			    			<%= link_to edit_group_path(@group) do%>
			    				<button type="button" class="btn btn-default btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Edit</button>
			    			<%end%>
			    			<%= link_to group_path(@group), :method=>:delete, :confirm => "Are you sure you want to delete?" do%>
			    				<button type="button" class="btn btn-default btn-xs"><i class="fa fa-trash-o" aria-hidden="true"></i>Delete</button>
			    			<%end%>
		    			</div> -->
			    	</div>		      
			    </div>
			</div>
		</div> <!-- /.group-conversation -->
		<div>
		<div id="group_posts_id">
			<%=render :partial => "group_messages/all_group_posts", :locals=>{:group_messages=>@group_messages, :group => @group}%>	
		</div>
      	
      </div>
	  </div> 
    <%= render :partial => "groups/group_members", :locals =>{:group => @group, :group_members => @group_users, :custom_class1 => "col-md-12", :custom_class => "col-md-4"} %>
  </div>
</div>